name: Build Development Container
on:
  push:
    branches: ["main"]
    paths:
      - 'docker/devel/**'
      - '.github/workflows/build-devel-container.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: java-trtllm-devel

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: '/var/lib/docker'

      - name: Restart Docker
        run: |
          sudo service docker restart
          docker system df
          df -h

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/devel
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

  test-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: '/var/lib/docker' # Crucial: This ensures the image pull goes to the large disk

      - name: Restart Docker
        run: |
          sudo service docker restart
          docker system df
          df -h

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/${{ github.repository_owner }}/java-trtllm-devel:latest

      - name: Check Java Version
        run: |
          docker run --rm \
          --entrypoint /bin/bash \
          ghcr.io/${{ github.repository_owner }}/java-trtllm-devel:latest \
          -c "java -version"

      - name: Verify Environment
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            ghcr.io/${{ github.repository_owner }}/java-trtllm-devel:latest \
            -c "echo 'Displaying OS info...' && cat /etc/os-release"