name: Build Development Container
on:
  push:
    branches: ["main"]
    paths:
      - 'docker/devel/**'
      - '.github/workflows/build-devel-container.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: java-trtllm-devel

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Maximize disk space
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/lib/google-cloud-sdk
          sudo docker system prune -a -f
          sudo apt-get clean
          
          echo "Disk space after cleanup:"
          df -h

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/devel
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

  test-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/java-trtllm-devel:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check Java Version
        run: java -version

      - name: Verify Environment
        run: |
          echo "Displaying OS info..."
          cat /etc/os-release